### ISSUE TITLE
make -f debian/rules build  fail

### ISSUE THREAD

**Issue by ManhTK1911** [elsampsa/valkka-core#18] opened 2020-07-05 14:41 UTC
i installing follow to guide, but at step 'proceed in building live555, ffmpeg and valkka', i try to run command:

make -f debian/rules build

It had isssue like log below:

, unsigned int, unsigned char*, unsigned int)':
SRTPCryptographicContext.cpp:(.text+0x2bd): undefined reference to `AES_set_encrypt_key'
SRTPCryptographicContext.cpp:(.text+0x2ea): undefined reference to `AES_encrypt'
../liveMedia/libliveMedia.a(SRTPCryptographicContext.o): In function `SRTPCryptographicContext::deriveSingleKey(unsigned char const*, unsigned char const*, SRTPCryptographicContext::SRTPKeyDerivationLabel, unsigned int, unsigned char*)':
SRTPCryptographicContext.cpp:(.text+0x7af): undefined reference to `AES_set_encrypt_key'
SRTPCryptographicContext.cpp:(.text+0x80b): undefined reference to `AES_encrypt'
../liveMedia/libliveMedia.a(HMAC_SHA1.o): In function `sha1(unsigned char*, unsigned char const*, unsigned int, unsigned char const*, unsigned int)':
HMAC_SHA1.cpp:(.text+0x1d): undefined reference to `EVP_MD_CTX_new'
HMAC_SHA1.cpp:(.text+0x25): undefined reference to `EVP_sha1'
HMAC_SHA1.cpp:(.text+0x30): undefined reference to `EVP_DigestInit'
HMAC_SHA1.cpp:(.text+0x3d): undefined reference to `EVP_DigestUpdate'
HMAC_SHA1.cpp:(.text+0x50): undefined reference to `EVP_DigestUpdate'
HMAC_SHA1.cpp:(.text+0x5d): undefined reference to `EVP_DigestFinal'
HMAC_SHA1.cpp:(.text+0x73): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
Makefile:105: recipe for target 'testMP3Streamer' failed
make[2]: *** [testMP3Streamer] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/valkka/valkka-core/ext/live/testProgs'
Makefile:35: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/valkka/valkka-core/ext/live'
debian/rules:26: recipe for target 'build' failed
make: *** [build] Error 2
valkka/valkka-core$ make -f debian/rules package
make -C /home/valkka/valkka-core/build_dir package
make[1]: *** /home/valkka/valkka-core/build_dir: No such file or directory.  Stop.
debian/rules:59: recipe for target 'package' failed
make: *** [package] Error 2

How can i solve it,

Thanks you

**Comment by elsampsa** [comment] 2020-07-05 16:17
Duplicate of https://github.com/elsampsa/valkka-core/issues/17

**Closed by elsampsa** 2020-07-05 16:17 UTC
